// <auto-generated />
using System;
using HealthApp.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealthApp.API.Migrations
{
    [DbContext(typeof(HealthAppDbContext))]
    [Migration("20260614192538_SeedDataToPatientTable")]
    partial class SeedDataToPatientTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HealthApp.API.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InsuranceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PatientId");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            PatientId = 1,
                            DateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "johnmathew@gmail.com",
                            Gender = "Male",
                            InsuranceId = "INS001",
                            PatientName = "John Mathew",
                            PhoneNumber = "8796534521"
                        },
                        new
                        {
                            PatientId = 2,
                            DateOfBirth = new DateTime(1985, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "rameshk@gmail.com",
                            Gender = "Male",
                            InsuranceId = "INS1002",
                            PatientName = "Ramesh Kumar",
                            PhoneNumber = "9876543210"
                        },
                        new
                        {
                            PatientId = 3,
                            DateOfBirth = new DateTime(1992, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "priya@gmail.com",
                            Gender = "Female",
                            InsuranceId = "INS1003",
                            PatientName = "Priya Sharma",
                            PhoneNumber = "8765432109"
                        },
                        new
                        {
                            PatientId = 4,
                            DateOfBirth = new DateTime(2000, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "arunraj@gmail.com",
                            Gender = "Male",
                            InsuranceId = "INS1004",
                            PatientName = "Arun Raj",
                            PhoneNumber = "7654321098"
                        },
                        new
                        {
                            PatientId = 5,
                            DateOfBirth = new DateTime(2001, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "meenu@gmail.com",
                            Gender = "Female",
                            InsuranceId = "INS1005",
                            PatientName = "Meena Devi",
                            PhoneNumber = "6543210987"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
