// <auto-generated />
using System;
using HealthApp.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealthApp.Api.Migrations
{
    [DbContext(typeof(HealthAppDbContext))]
    [Migration("20260710122810_AddDoctorLeave")]
    partial class AddDoctorLeave
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HealthApp.Api.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId")
                        .IsUnique()
                        .HasFilter("[DoctorId] IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("PatientId")
                        .IsUnique()
                        .HasFilter("[PatientId] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("HealthApp.Api.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<string>("CancellationReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ScheduledDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TimeSlot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AppointmentId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            AppointmentId = 1001,
                            DoctorId = 1,
                            PatientId = 1,
                            ScheduledDate = new DateOnly(2025, 10, 15),
                            Status = 3,
                            TimeSlot = "09:00 AM - 09:30 AM"
                        },
                        new
                        {
                            AppointmentId = 1002,
                            DoctorId = 2,
                            PatientId = 2,
                            ScheduledDate = new DateOnly(2025, 11, 20),
                            Status = 3,
                            TimeSlot = "10:00 AM - 10:30 AM"
                        },
                        new
                        {
                            AppointmentId = 1003,
                            DoctorId = 3,
                            PatientId = 3,
                            ScheduledDate = new DateOnly(2026, 1, 10),
                            Status = 3,
                            TimeSlot = "11:30 AM - 12:00 PM"
                        },
                        new
                        {
                            AppointmentId = 1004,
                            DoctorId = 4,
                            PatientId = 4,
                            ScheduledDate = new DateOnly(2026, 2, 14),
                            Status = 3,
                            TimeSlot = "02:00 PM - 02:30 PM"
                        },
                        new
                        {
                            AppointmentId = 1005,
                            CancellationReason = "Patient had a sudden family emergency.",
                            DoctorId = 5,
                            PatientId = 5,
                            ScheduledDate = new DateOnly(2026, 4, 10),
                            Status = 2,
                            TimeSlot = "04:00 PM - 04:30 PM"
                        },
                        new
                        {
                            AppointmentId = 1006,
                            DoctorId = 1,
                            PatientId = 6,
                            ScheduledDate = new DateOnly(2026, 8, 15),
                            Status = 1,
                            TimeSlot = "09:00 AM - 09:30 AM"
                        },
                        new
                        {
                            AppointmentId = 1007,
                            DoctorId = 2,
                            PatientId = 7,
                            ScheduledDate = new DateOnly(2026, 9, 16),
                            Status = 1,
                            TimeSlot = "10:00 AM - 10:30 AM"
                        },
                        new
                        {
                            AppointmentId = 1008,
                            DoctorId = 3,
                            PatientId = 8,
                            ScheduledDate = new DateOnly(2026, 10, 17),
                            Status = 1,
                            TimeSlot = "11:30 AM - 12:00 PM"
                        },
                        new
                        {
                            AppointmentId = 1009,
                            DoctorId = 4,
                            PatientId = 9,
                            ScheduledDate = new DateOnly(2026, 11, 20),
                            Status = 0,
                            TimeSlot = "02:00 PM - 02:30 PM"
                        },
                        new
                        {
                            AppointmentId = 1010,
                            DoctorId = 5,
                            PatientId = 10,
                            ScheduledDate = new DateOnly(2026, 12, 5),
                            Status = 0,
                            TimeSlot = "04:00 PM - 04:30 PM"
                        });
                });

            modelBuilder.Entity("HealthApp.Api.Models.Doctor", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoctorId"));

                    b.Property<decimal>("ConsultationFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DoctorEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("DoctorPhoneNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Specialisation")
                        .HasColumnType("int");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("DoctorId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            DoctorId = 1,
                            ConsultationFee = 600.00m,
                            DoctorEmail = "gregory.house@healthapp.com",
                            DoctorPhoneNo = "9000000101",
                            FullName = "Dr. Gregory House",
                            IsActive = true,
                            Specialisation = 0,
                            YearsOfExperience = 15
                        },
                        new
                        {
                            DoctorId = 2,
                            ConsultationFee = 500.00m,
                            DoctorEmail = "lisa.cuddy@healthapp.com",
                            DoctorPhoneNo = "9000000102",
                            FullName = "Dr. Lisa Cuddy",
                            IsActive = true,
                            Specialisation = 8,
                            YearsOfExperience = 12
                        },
                        new
                        {
                            DoctorId = 3,
                            ConsultationFee = 1000.00m,
                            DoctorEmail = "derek.shepherd@healthapp.com",
                            DoctorPhoneNo = "9000000103",
                            FullName = "Dr. Derek Shepherd",
                            IsActive = true,
                            Specialisation = 3,
                            YearsOfExperience = 18
                        },
                        new
                        {
                            DoctorId = 4,
                            ConsultationFee = 450.00m,
                            DoctorEmail = "meredith.grey@healthapp.com",
                            DoctorPhoneNo = "9000000104",
                            FullName = "Dr. Meredith Grey",
                            IsActive = true,
                            Specialisation = 0,
                            YearsOfExperience = 8
                        },
                        new
                        {
                            DoctorId = 5,
                            ConsultationFee = 750.00m,
                            DoctorEmail = "cristina.yang@healthapp.com",
                            DoctorPhoneNo = "9000000105",
                            FullName = "Dr. Cristina Yang",
                            IsActive = true,
                            Specialisation = 1,
                            YearsOfExperience = 10
                        },
                        new
                        {
                            DoctorId = 6,
                            ConsultationFee = 800.00m,
                            DoctorEmail = "richard.webber@healthapp.com",
                            DoctorPhoneNo = "9000000106",
                            FullName = "Dr. Richard Webber",
                            IsActive = true,
                            Specialisation = 0,
                            YearsOfExperience = 30
                        },
                        new
                        {
                            DoctorId = 7,
                            ConsultationFee = 550.00m,
                            DoctorEmail = "miranda.bailey@healthapp.com",
                            DoctorPhoneNo = "9000000107",
                            FullName = "Dr. Miranda Bailey",
                            IsActive = true,
                            Specialisation = 0,
                            YearsOfExperience = 14
                        },
                        new
                        {
                            DoctorId = 8,
                            ConsultationFee = 400.00m,
                            DoctorEmail = "alex.karev@healthapp.com",
                            DoctorPhoneNo = "9000000108",
                            FullName = "Dr. Alex Karev",
                            IsActive = true,
                            Specialisation = 5,
                            YearsOfExperience = 7
                        },
                        new
                        {
                            DoctorId = 9,
                            ConsultationFee = 650.00m,
                            DoctorEmail = "jackson.avery@healthapp.com",
                            DoctorPhoneNo = "9000000109",
                            FullName = "Dr. Jackson Avery",
                            IsActive = true,
                            Specialisation = 7,
                            YearsOfExperience = 9
                        },
                        new
                        {
                            DoctorId = 10,
                            ConsultationFee = 400.00m,
                            DoctorEmail = "april.kepner@healthapp.com",
                            DoctorPhoneNo = "9000000110",
                            FullName = "Dr. April Kepner",
                            IsActive = true,
                            Specialisation = 4,
                            YearsOfExperience = 6
                        });
                });

            modelBuilder.Entity("HealthApp.Api.Models.DoctorLeave", b =>
                {
                    b.Property<int>("DoctorLeaveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoctorLeaveId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("DoctorLeaveId");

                    b.HasIndex("DoctorId");

                    b.ToTable("DoctorLeaves");
                });

            modelBuilder.Entity("HealthApp.Api.Models.HealthRecord", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecordId"));

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Prescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("VisitDate")
                        .HasColumnType("date");

                    b.HasKey("RecordId");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("HealthRecords");

                    b.HasData(
                        new
                        {
                            RecordId = 1001,
                            AppointmentId = 1001,
                            Diagnosis = "Essential Hypertension",
                            DoctorId = 1,
                            Notes = "Patient educated on low sodium diet.",
                            PatientId = 1,
                            Prescription = "Lisinopril 10mg daily",
                            VisitDate = new DateOnly(2025, 10, 15)
                        },
                        new
                        {
                            RecordId = 1002,
                            AppointmentId = 1002,
                            Diagnosis = "Routine Pregnancy Checkup",
                            DoctorId = 2,
                            Notes = "Fetal heart rate normal. Continue regular checkups.",
                            PatientId = 2,
                            Prescription = "Prenatal Vitamins",
                            VisitDate = new DateOnly(2025, 11, 20)
                        },
                        new
                        {
                            RecordId = 1003,
                            AppointmentId = 1003,
                            Diagnosis = "Migraine with Aura",
                            DoctorId = 3,
                            Notes = "Advised to keep a headache diary to identify triggers.",
                            PatientId = 3,
                            Prescription = "Sumatriptan 50mg as needed",
                            VisitDate = new DateOnly(2026, 1, 10)
                        },
                        new
                        {
                            RecordId = 1004,
                            AppointmentId = 1004,
                            Diagnosis = "Acute Bronchitis",
                            DoctorId = 4,
                            Notes = "Rest and hydration recommended.",
                            PatientId = 4,
                            Prescription = "Azithromycin 500mg daily",
                            VisitDate = new DateOnly(2026, 2, 14)
                        });
                });

            modelBuilder.Entity("HealthApp.Api.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RecipientUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RelatedEntityId")
                        .HasColumnType("int");

                    b.Property<string>("RelatedEntityType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("NotificationId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("HealthApp.Api.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InsuranceId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PatientId");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            PatientId = 1,
                            CreatedDate = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1985, 4, 12),
                            Email = "michael.j@gmail.com",
                            FullName = "Michael Johnson",
                            Gender = "Male",
                            InsuranceId = "INS-1001",
                            PhoneNumber = "8000000501"
                        },
                        new
                        {
                            PatientId = 2,
                            CreatedDate = new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1990, 8, 25),
                            Email = "sarah.w@gmail.com",
                            FullName = "Sarah Williams",
                            Gender = "Female",
                            InsuranceId = "INS-1002",
                            PhoneNumber = "8000000502"
                        },
                        new
                        {
                            PatientId = 3,
                            CreatedDate = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1978, 2, 14),
                            Email = "david.b@gmail.com",
                            FullName = "David Brown",
                            Gender = "Male",
                            InsuranceId = "INS-1003",
                            PhoneNumber = "8000000503"
                        },
                        new
                        {
                            PatientId = 4,
                            CreatedDate = new DateTime(2025, 1, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1995, 11, 30),
                            Email = "emily.d@gmail.com",
                            FullName = "Emily Davis",
                            Gender = "Female",
                            InsuranceId = "INS-1004",
                            PhoneNumber = "8000000504"
                        },
                        new
                        {
                            PatientId = 5,
                            CreatedDate = new DateTime(2025, 1, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1982, 7, 19),
                            Email = "james.m@gmail.com",
                            FullName = "James Miller",
                            Gender = "Male",
                            InsuranceId = "INS-1005",
                            PhoneNumber = "8000000505"
                        },
                        new
                        {
                            PatientId = 6,
                            CreatedDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1988, 9, 5),
                            Email = "jessica.w@gmail.com",
                            FullName = "Jessica Wilson",
                            Gender = "Female",
                            InsuranceId = "INS-1006",
                            PhoneNumber = "8000000506"
                        },
                        new
                        {
                            PatientId = 7,
                            CreatedDate = new DateTime(2025, 1, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1970, 12, 1),
                            Email = "robert.m@gmail.com",
                            FullName = "Robert Moore",
                            Gender = "Male",
                            InsuranceId = "INS-1007",
                            PhoneNumber = "8000000507"
                        },
                        new
                        {
                            PatientId = 8,
                            CreatedDate = new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1992, 3, 22),
                            Email = "amanda.t@gmail.com",
                            FullName = "Amanda Taylor",
                            Gender = "Female",
                            InsuranceId = "INS-1008",
                            PhoneNumber = "8000000508"
                        },
                        new
                        {
                            PatientId = 9,
                            CreatedDate = new DateTime(2025, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1980, 5, 17),
                            Email = "william.a@gmail.com",
                            FullName = "William Anderson",
                            Gender = "Male",
                            InsuranceId = "INS-1009",
                            PhoneNumber = "8000000509"
                        },
                        new
                        {
                            PatientId = 10,
                            CreatedDate = new DateTime(2025, 1, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1998, 10, 8),
                            Email = "ashley.t@gmail.com",
                            FullName = "Ashley Thomas",
                            Gender = "Female",
                            InsuranceId = "INS-1010",
                            PhoneNumber = "8000000510"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HealthApp.Api.Models.ApplicationUser", b =>
                {
                    b.HasOne("HealthApp.Api.Models.Doctor", "Doctor")
                        .WithOne("User")
                        .HasForeignKey("HealthApp.Api.Models.ApplicationUser", "DoctorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HealthApp.Api.Models.Patient", "Patient")
                        .WithOne("User")
                        .HasForeignKey("HealthApp.Api.Models.ApplicationUser", "PatientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HealthApp.Api.Models.Appointment", b =>
                {
                    b.HasOne("HealthApp.Api.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthApp.Api.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HealthApp.Api.Models.DoctorLeave", b =>
                {
                    b.HasOne("HealthApp.Api.Models.Doctor", "Doctor")
                        .WithMany("DoctorLeaves")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("HealthApp.Api.Models.HealthRecord", b =>
                {
                    b.HasOne("HealthApp.Api.Models.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId");

                    b.HasOne("HealthApp.Api.Models.Doctor", "Doctor")
                        .WithMany("HealthRecords")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthApp.Api.Models.Patient", "Patient")
                        .WithMany("HealthRecords")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HealthApp.Api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HealthApp.Api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthApp.Api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HealthApp.Api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthApp.Api.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("DoctorLeaves");

                    b.Navigation("HealthRecords");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthApp.Api.Models.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("HealthRecords");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
