// <auto-generated />
namespace HealthCare_Appointment_Portal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class DBonmodelChanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DBonmodelChanges));
        
        string IMigrationMetadata.Id
        {
            get { return "202606121221283_DBonmodelChanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
