sonar.projectKey=HealthAxis
sonar.working.directory=C:\\Users\\287802\\source\\repos\\HealthAxisApi\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\Users\\287802\\source\\repos\\HealthAxisApi
sonar.pullrequest.cache.basepath=C:\\Users\\287802\\source\\repos\\HealthAxisApi
sonar.sources=\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\.vs\\HealthAxisApi.slnx\\config\\applicationhost.config",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\.vs\\HealthAxisApi.slnx\\v18\\DocumentLayout.backup.json",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\.vs\\HealthAxisApi.slnx\\v18\\DocumentLayout.json"

05BD55AB-6EEB-7356-0349-B0F2F9348407.sonar.projectKey=HealthAxis:05BD55AB-6EEB-7356-0349-B0F2F9348407
05BD55AB-6EEB-7356-0349-B0F2F9348407.sonar.projectName=HealthAxisCore_Api
05BD55AB-6EEB-7356-0349-B0F2F9348407.sonar.projectBaseDir=C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi
05BD55AB-6EEB-7356-0349-B0F2F9348407.sonar.sourceEncoding=utf-8
05BD55AB-6EEB-7356-0349-B0F2F9348407.sonar.sources=
05BD55AB-6EEB-7356-0349-B0F2F9348407.sonar.tests=\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\Controllers\\AppointmentController.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\Controllers\\AuthController.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\Controllers\\DoctorController.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\Controllers\\HealthRecordController.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\Controllers\\PatientController.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\Data\\AdminSeeder.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\Data\\HealthAppDbContext.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\Data\\RoleSeeder.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\DTOs\\Appointment\\AppointmentResponseDTO.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\DTOs\\Appointment\\CreateAppointmentDTO.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\DTOs\\Common\\ErrorResponse.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\DTOs\\Doctor\\CreateDoctorDTO.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\DTOs\\Doctor\\DoctorResponseDTO.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\DTOs\\HealthRecord\\CreateHealthRecordDTO.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\DTOs\\HealthRecord\\HealthRecordResponseDTO.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\DTOs\\Patient\\CreatePatientDTO.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\DTOs\\Patient\\PatientResponseDTO.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\DTOs\\Patient\\UpdatePatientDTO.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\DTOs\\User\\AuthResponseDTO.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\DTOs\\User\\ChangePasswordDTO.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\DTOs\\User\\LoginDTO.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\DTOs\\User\\RegisterDTO.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\Enums\\AppointmentStatus.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\Enums\\GenderType.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\Enums\\SpecialisationType.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\Enums\\UserRole.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\Exceptions\\AppointmentRuleException.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\Exceptions\\BusinessRuleException.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\Exceptions\\EntityNotFoundException.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\Exceptions\\HealthCareAppException.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\Exceptions\\UnauthorizedException.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\Mappings\\MappingProfile.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\Middleware\\GlobalExceptionHandler.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\Migrations\\20260616150715_InitialIdentitySetup.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\Migrations\\20260616150715_InitialIdentitySetup.Designer.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\Migrations\\20260618092712_UpdateApplicationUser.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\Migrations\\20260618092712_UpdateApplicationUser.Designer.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\Migrations\\20260618180348_AddDoctorEmailAndDoctorOnboardingFields.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\Migrations\\20260618180348_AddDoctorEmailAndDoctorOnboardingFields.Designer.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\Migrations\\HealthAppDbContextModelSnapshot.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\Models\\ApplicationUser.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\Models\\Appointment.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\Models\\Doctor.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\Models\\HealthRecord.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\Models\\Patient.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\Program.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\Repositories\\Implementation\\AppointmentRepository.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\Repositories\\Implementation\\DoctorRepository.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\Repositories\\Implementation\\GenericRepository.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\Repositories\\Implementation\\HealthRecordRepository.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\Repositories\\Implementation\\PatientRepository.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\Repositories\\Interface\\IAppointmentRepository.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\Repositories\\Interface\\IDoctorRepository.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\Repositories\\Interface\\IGenericRepository.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\Repositories\\Interface\\IHealthRecordRepository.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\Repositories\\Interface\\IPatientRepository.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\Services\\Implementation\\AppointmentService.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\Services\\Implementation\\AuthService.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\Services\\Implementation\\DoctorService.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\Services\\Implementation\\HealthRecordService.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\Services\\Implementation\\PatientService.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\Services\\Interfaces\\IAppointmentService.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\Services\\Interfaces\\IAuthService.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\Services\\Interfaces\\IDoctorService.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\Services\\Interfaces\\IHealthRecordService.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\Services\\Interfaces\\IPateintService.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\obj\\Debug\\net10.0\\HealthAxisCore_Api.GlobalUsings.g.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\obj\\Debug\\net10.0\\.NETCoreApp,Version=v10.0.AssemblyAttributes.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\obj\\Debug\\net10.0\\HealthAxisCore_Api.AssemblyInfo.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\obj\\Debug\\net10.0\\HealthAxisCore_Api.MvcApplicationPartsAssemblyInfo.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\appsettings.Development.json",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\appsettings.json",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\HealthAxisApi.http",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\Properties\\launchSettings.json",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\obj\\HealthAxisApi.csproj.nuget.dgspec.json",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\obj\\HealthAxisCore_Api.csproj.nuget.dgspec.json",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\obj\\project.assets.json",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\bin\\Debug\\net10.0\\appsettings.Development.json",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\bin\\Debug\\net10.0\\appsettings.json",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\bin\\Debug\\net10.0\\HealthAxisCore_Api.deps.json",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\bin\\Debug\\net10.0\\HealthAxisCore_Api.runtimeconfig.json",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\bin\\Debug\\net10.0\\HealthAxisCore_Api.staticwebassets.endpoints.json",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\obj\\Debug\\net10.0\\ApiEndpoints.json",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\obj\\Debug\\net10.0\\HealthAxisCore_Api.sourcelink.json",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\obj\\Debug\\net10.0\\rjsmcshtml.dswa.cache.json",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\obj\\Debug\\net10.0\\rjsmrazor.dswa.cache.json",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\obj\\Debug\\net10.0\\rpswa.dswa.cache.json",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\obj\\Debug\\net10.0\\staticwebassets.build.endpoints.json",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\obj\\Debug\\net10.0\\staticwebassets.build.json",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\bin\\Debug\\net10.0\\BuildHost-net472\\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.exe.config",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\bin\\Debug\\net10.0\\BuildHost-netcore\\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.deps.json",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\bin\\Debug\\net10.0\\BuildHost-netcore\\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.runtimeconfig.json",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisApi\\obj\\Debug\\net10.0\\EndpointInfo\\HealthAxisCore_Api.json"

05BD55AB-6EEB-7356-0349-B0F2F9348407.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\.sonarqube\\out\\0"
05BD55AB-6EEB-7356-0349-B0F2F9348407.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\.sonarqube\\out\\0\\Issues.json"
05BD55AB-6EEB-7356-0349-B0F2F9348407.sonar.cs.scanner.telemetry=\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\.sonarqube\\out\\0\\Telemetry.json"

05BD55AB-6EEB-7356-0349-B0F2F9348407.sonar.working.directory=C:\\Users\\287802\\source\\repos\\HealthAxisApi\\.sonarqube\\out\\.sonar\\mod0
7CF44F4D-C1BE-4BC1-AC96-6FA94D0FB386.sonar.projectKey=HealthAxis:7CF44F4D-C1BE-4BC1-AC96-6FA94D0FB386
7CF44F4D-C1BE-4BC1-AC96-6FA94D0FB386.sonar.projectName=HealthAxisCore_Api.Tests
7CF44F4D-C1BE-4BC1-AC96-6FA94D0FB386.sonar.projectBaseDir=C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisCore_Api.Tests
7CF44F4D-C1BE-4BC1-AC96-6FA94D0FB386.sonar.sourceEncoding=utf-8
7CF44F4D-C1BE-4BC1-AC96-6FA94D0FB386.sonar.sources=
7CF44F4D-C1BE-4BC1-AC96-6FA94D0FB386.sonar.tests=\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisCore_Api.Tests\\obj\\HealthAxisCore_Api.Tests.csproj.nuget.dgspec.json",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisCore_Api.Tests\\obj\\project.assets.json",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisCore_Api.Tests\\bin\\Debug\\net10.0\\appsettings.Development.json",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisCore_Api.Tests\\bin\\Debug\\net10.0\\appsettings.json",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisCore_Api.Tests\\bin\\Debug\\net10.0\\HealthAxisCore_Api.deps.json",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisCore_Api.Tests\\bin\\Debug\\net10.0\\HealthAxisCore_Api.runtimeconfig.json",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisCore_Api.Tests\\bin\\Debug\\net10.0\\HealthAxisCore_Api.staticwebassets.endpoints.json",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisCore_Api.Tests\\bin\\Debug\\net10.0\\HealthAxisCore_Api.Tests.deps.json",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisCore_Api.Tests\\bin\\Debug\\net10.0\\HealthAxisCore_Api.Tests.runtimeconfig.json",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisCore_Api.Tests\\obj\\Debug\\net10.0\\HealthAxisCore_Api.Tests.sourcelink.json",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisCore_Api.Tests\\Helpers\\MapperHelper.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisCore_Api.Tests\\Services\\AppointmentServiceTest.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisCore_Api.Tests\\Services\\AuthServiceTest.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisCore_Api.Tests\\Services\\DoctorServiceTest.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisCore_Api.Tests\\Services\\HealthRecordServiceTest.cs",\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\HealthAxisCore_Api.Tests\\Services\\PatientServiceTest.cs"

7CF44F4D-C1BE-4BC1-AC96-6FA94D0FB386.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\.sonarqube\\out\\1"
7CF44F4D-C1BE-4BC1-AC96-6FA94D0FB386.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\.sonarqube\\out\\1\\Issues.json"
7CF44F4D-C1BE-4BC1-AC96-6FA94D0FB386.sonar.cs.scanner.telemetry=\
"C:\\Users\\287802\\source\\repos\\HealthAxisApi\\.sonarqube\\out\\1\\Telemetry.json"

7CF44F4D-C1BE-4BC1-AC96-6FA94D0FB386.sonar.working.directory=C:\\Users\\287802\\source\\repos\\HealthAxisApi\\.sonarqube\\out\\.sonar\\mod1
sonar.host.url=http://localhost:9000
sonar.visualstudio.enable=false

sonar.modules=05BD55AB-6EEB-7356-0349-B0F2F9348407,7CF44F4D-C1BE-4BC1-AC96-6FA94D0FB386

