sonar.projectKey=HealthAxis
sonar.working.directory=C:\\Users\\310033\\source\\repos\\HealthAxis\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\Users\\310033\\source\\repos\\HealthAxis
sonar.pullrequest.cache.basepath=C:\\Users\\310033\\source\\repos\\HealthAxis
sonar.sources=\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\.vs\\HealthAxis.slnx\\v18\\DocumentLayout.backup.json",\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\.vs\\HealthAxis.slnx\\v18\\DocumentLayout.json"

4F3F1264-C090-480F-9A42-E5B611B935D6.sonar.projectKey=HealthAxis:4F3F1264-C090-480F-9A42-E5B611B935D6
4F3F1264-C090-480F-9A42-E5B611B935D6.sonar.projectName=HealthAxisApplicn
4F3F1264-C090-480F-9A42-E5B611B935D6.sonar.projectBaseDir=C:\\Users\\310033\\source\\repos\\HealthAxis\\HealthAxisApplicn
4F3F1264-C090-480F-9A42-E5B611B935D6.sonar.sourceEncoding=utf-8
4F3F1264-C090-480F-9A42-E5B611B935D6.sonar.tests=
4F3F1264-C090-480F-9A42-E5B611B935D6.sonar.sources=\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\HealthAxisApplicn\\Data\\AppDbContext.cs",\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\HealthAxisApplicn\\Dto\\AppointmentDto.cs",\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\HealthAxisApplicn\\Dto\\DoctorDto.cs",\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\HealthAxisApplicn\\Dto\\HealthRecordDto.cs",\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\HealthAxisApplicn\\Dto\\PatientDto.cs",\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\HealthAxisApplicn\\Dto\\UserDto.cs",\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\HealthAxisApplicn\\Mappings\\MappingProfile.cs",\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\HealthAxisApplicn\\Models\\Appointment.cs",\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\HealthAxisApplicn\\Models\\Doctor.cs",\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\HealthAxisApplicn\\Models\\HealthRecord.cs",\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\HealthAxisApplicn\\Models\\Patient.cs",\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\HealthAxisApplicn\\Models\\User.cs",\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\HealthAxisApplicn\\Program.cs",\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\HealthAxisApplicn\\Repositories\\IAppointmentRepository.cs",\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\HealthAxisApplicn\\Repositories\\IDoctorRepository.cs",\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\HealthAxisApplicn\\Repositories\\IHealthRecordRepository.cs",\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\HealthAxisApplicn\\Repositories\\Impl\\AppointmentRepository.cs",\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\HealthAxisApplicn\\Repositories\\Impl\\DoctorRepository.cs",\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\HealthAxisApplicn\\Repositories\\Impl\\HealthRecordRepository.cs",\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\HealthAxisApplicn\\Repositories\\Impl\\PatientRepository.cs",\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\HealthAxisApplicn\\Repositories\\Impl\\Repository.cs",\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\HealthAxisApplicn\\Repositories\\IPatientRepository.cs",\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\HealthAxisApplicn\\Repositories\\IRepository.cs",\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\HealthAxisApplicn\\Services\\IAppointmentService.cs",\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\HealthAxisApplicn\\Services\\IDoctorService.cs",\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\HealthAxisApplicn\\Services\\IHealthRecordService.cs",\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\HealthAxisApplicn\\Services\\Impl\\AppointmentService.cs",\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\HealthAxisApplicn\\Services\\Impl\\DoctorService.cs",\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\HealthAxisApplicn\\Services\\Impl\\HealthRecordService.cs",\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\HealthAxisApplicn\\Services\\Impl\\PatientService.cs",\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\HealthAxisApplicn\\Services\\IPatientService.cs",\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\HealthAxisApplicn\\obj\\Debug\\net10.0\\HealthAxisApplicn.GlobalUsings.g.cs",\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\HealthAxisApplicn\\obj\\Debug\\net10.0\\.NETCoreApp,Version=v10.0.AssemblyAttributes.cs",\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\HealthAxisApplicn\\obj\\Debug\\net10.0\\HealthAxisApplicn.AssemblyInfo.cs",\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\HealthAxisApplicn\\obj\\Debug\\net10.0\\HealthAxisApplicn.MvcApplicationPartsAssemblyInfo.cs",\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\HealthAxisApplicn\\appsettings.Development.json",\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\HealthAxisApplicn\\appsettings.json",\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\HealthAxisApplicn\\HealthAxisApplicn.http",\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\HealthAxisApplicn\\Properties\\launchSettings.json",\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\HealthAxisApplicn\\obj\\HealthAxisApplicn.csproj.nuget.dgspec.json",\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\HealthAxisApplicn\\obj\\project.assets.json",\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\HealthAxisApplicn\\bin\\Debug\\net10.0\\appsettings.Development.json",\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\HealthAxisApplicn\\bin\\Debug\\net10.0\\appsettings.json",\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\HealthAxisApplicn\\bin\\Debug\\net10.0\\HealthAxisApplicn.deps.json",\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\HealthAxisApplicn\\bin\\Debug\\net10.0\\HealthAxisApplicn.runtimeconfig.json",\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\HealthAxisApplicn\\bin\\Debug\\net10.0\\HealthAxisApplicn.staticwebassets.endpoints.json",\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\HealthAxisApplicn\\obj\\Debug\\net10.0\\rjsmcshtml.dswa.cache.json",\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\HealthAxisApplicn\\obj\\Debug\\net10.0\\rjsmrazor.dswa.cache.json",\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\HealthAxisApplicn\\obj\\Debug\\net10.0\\rpswa.dswa.cache.json",\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\HealthAxisApplicn\\obj\\Debug\\net10.0\\staticwebassets.build.endpoints.json",\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\HealthAxisApplicn\\obj\\Debug\\net10.0\\staticwebassets.build.json",\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\HealthAxisApplicn\\bin\\Debug\\net10.0\\BuildHost-net472\\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.exe.config",\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\HealthAxisApplicn\\bin\\Debug\\net10.0\\BuildHost-netcore\\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.deps.json",\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\HealthAxisApplicn\\bin\\Debug\\net10.0\\BuildHost-netcore\\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.runtimeconfig.json"

4F3F1264-C090-480F-9A42-E5B611B935D6.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\.sonarqube\\out\\1"
4F3F1264-C090-480F-9A42-E5B611B935D6.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\.sonarqube\\out\\1\\Issues.json"
4F3F1264-C090-480F-9A42-E5B611B935D6.sonar.cs.scanner.telemetry=\
"C:\\Users\\310033\\source\\repos\\HealthAxis\\.sonarqube\\out\\1\\Telemetry.json"

4F3F1264-C090-480F-9A42-E5B611B935D6.sonar.working.directory=C:\\Users\\310033\\source\\repos\\HealthAxis\\.sonarqube\\out\\.sonar\\mod0
sonar.host.url=http://localhost:9000
sonar.visualstudio.enable=false

sonar.modules=4F3F1264-C090-480F-9A42-E5B611B935D6

