sonar.projectKey=HealthApp
sonar.projectName=HealthApp
sonar.working.directory=C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp
sonar.pullrequest.cache.basepath=C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp
sonar.sources=\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\.vs\\HealthApp.slnx\\v18\\DocumentLayout.backup.json",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\.vs\\HealthApp.slnx\\v18\\DocumentLayout.json",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\dotnet-tools.json"

14164E3D-8A75-A4DA-EE92-D8290D864931.sonar.projectKey=HealthApp:14164E3D-8A75-A4DA-EE92-D8290D864931
14164E3D-8A75-A4DA-EE92-D8290D864931.sonar.projectName=HealthApp
14164E3D-8A75-A4DA-EE92-D8290D864931.sonar.projectBaseDir=C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthApp
14164E3D-8A75-A4DA-EE92-D8290D864931.sonar.sourceEncoding=utf-8
14164E3D-8A75-A4DA-EE92-D8290D864931.sonar.tests=
14164E3D-8A75-A4DA-EE92-D8290D864931.sonar.sources=\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Constants\\TimeSlots.cs",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Databases\\AppointmentDb.cs",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Databases\\DoctorDb.cs",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Databases\\HealthRecordDb.cs",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Databases\\PatientDb.cs",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Exceptions\\AppointmentAlreadyCancelledException.cs",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Exceptions\\AppointmentAlreadyCompletedException.cs",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Exceptions\\AppointmentAlreadyConfirmedException.cs",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Exceptions\\AppointmentConflictException.cs",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Exceptions\\AppointmentNotFoundException.cs",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Exceptions\\DoctorNotFoundException.cs",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Exceptions\\DoctorUnavailableException.cs",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Exceptions\\InvalidDateRangeException.cs",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Exceptions\\InvalidSlotException.cs",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Exceptions\\NoAppointmentsFoundException.cs",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Exceptions\\NoDoctorsRegisteredException.cs",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Exceptions\\NoHealthRecordAvailableException.cs",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Exceptions\\NoPatientRegisteredException.cs",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Exceptions\\PastDateException.cs",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Exceptions\\PatientNotFoundException.cs",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Exceptions\\SlotAlreadyOverException.cs",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Menus\\DoctorMenu.cs",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Menus\\PatientMenu.cs",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Models\\Appointment.cs",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Models\\Doctor.cs",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Models\\HealthRecords.cs",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Models\\Patient.cs",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Program.cs",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Repository\\Impl\\AppointmentRepository.cs",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Repository\\Impl\\DoctorRepository.cs",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Repository\\Impl\\HealthRecordRepository.cs",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Repository\\Impl\\PatientRepository.cs",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Repository\\Interface\\IAppointmentRepository.cs",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Repository\\Interface\\IDoctorRepository.cs",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Repository\\Interface\\IHealthRecordRepository.cs",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Repository\\Interface\\IPatientRepository.cs",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Service\\Impl\\AppointmentService.cs",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Service\\Impl\\DoctorService.cs",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Service\\Impl\\HealthRecordService.cs",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Service\\Impl\\PatientService.cs",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Service\\Interface\\IAppointmentService.cs",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Service\\Interface\\IDoctorService.cs",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Service\\Interface\\IHealthRecordService.cs",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Service\\Interface\\IPatientService.cs",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthApp\\obj\\HealthApp.csproj.nuget.dgspec.json",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthApp\\obj\\project.assets.json",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthApp\\bin\\Debug\\net10.0\\HealthApp.deps.json",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthApp\\bin\\Debug\\net10.0\\HealthApp.runtimeconfig.json",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthApp\\obj\\Debug\\net10.0\\HealthApp.sourcelink.json"

14164E3D-8A75-A4DA-EE92-D8290D864931.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\.sonarqube\\out\\0"
14164E3D-8A75-A4DA-EE92-D8290D864931.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\.sonarqube\\out\\0\\Issues.json"
14164E3D-8A75-A4DA-EE92-D8290D864931.sonar.cs.scanner.telemetry=\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\.sonarqube\\out\\0\\Telemetry.json"

14164E3D-8A75-A4DA-EE92-D8290D864931.sonar.working.directory=C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\.sonarqube\\out\\.sonar\\mod0
FFBE01E7-18F9-8709-5BDC-64235E150587.sonar.projectKey=HealthApp:FFBE01E7-18F9-8709-5BDC-64235E150587
FFBE01E7-18F9-8709-5BDC-64235E150587.sonar.projectName=HealthAppTests
FFBE01E7-18F9-8709-5BDC-64235E150587.sonar.projectBaseDir=C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthAppTests
FFBE01E7-18F9-8709-5BDC-64235E150587.sonar.sourceEncoding=utf-8
FFBE01E7-18F9-8709-5BDC-64235E150587.sonar.sources=
FFBE01E7-18F9-8709-5BDC-64235E150587.sonar.tests=\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthAppTests\\obj\\HealthAppTests.csproj.nuget.dgspec.json",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthAppTests\\obj\\project.assets.json",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthAppTests\\bin\\Debug\\net10.0\\HealthApp.deps.json",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthAppTests\\bin\\Debug\\net10.0\\HealthApp.runtimeconfig.json",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthAppTests\\bin\\Debug\\net10.0\\HealthAppTests.deps.json",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthAppTests\\bin\\Debug\\net10.0\\HealthAppTests.runtimeconfig.json",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthAppTests\\obj\\Debug\\net10.0\\HealthAppTests.sourcelink.json",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthAppTests\\Repository Layer\\AppointmentRepositoryTests.cs",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthAppTests\\Repository Layer\\DoctorRepositoryTests.cs",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthAppTests\\Repository Layer\\HealthRecordRepositoryTests.cs",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthAppTests\\Repository Layer\\PatientRepositoryTests.cs",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthAppTests\\Service Layer\\AppointmentServiceTests.cs",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthAppTests\\Service Layer\\DoctorServiceTests.cs",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthAppTests\\Service Layer\\HealthRecordServiceTests.cs",\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\HealthAppTests\\Service Layer\\PatientServiceTests.cs"

FFBE01E7-18F9-8709-5BDC-64235E150587.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\.sonarqube\\out\\1"
FFBE01E7-18F9-8709-5BDC-64235E150587.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\.sonarqube\\out\\1\\Issues.json"
FFBE01E7-18F9-8709-5BDC-64235E150587.sonar.cs.scanner.telemetry=\
"C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\.sonarqube\\out\\1\\Telemetry.json"

FFBE01E7-18F9-8709-5BDC-64235E150587.sonar.working.directory=C:\\Users\\310507\\project\\Main_HAP_Pod1\\HealthApp\\.sonarqube\\out\\.sonar\\mod1
sonar.host.url=http://localhost:9000
sonar.cs.vscoveragexml.reportsPaths=coverage.xml
sonar.exclusions=**/Databases/**,**/Models/**,**/Constants/**,**/Exceptions/**,**/Menus/**,**/Program.cs,coverage.xml
sonar.visualstudio.enable=false

sonar.modules=14164E3D-8A75-A4DA-EE92-D8290D864931,FFBE01E7-18F9-8709-5BDC-64235E150587

