//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthCareWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorLeaf
    {
        public int Id { get; set; }
        public int DoctorId { get; set; }
        public System.DateTime LeaveDate { get; set; }
        public string Reason { get; set; }
    
        public virtual Doctor Doctor { get; set; }
    }
}
