//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthCareWebApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
     
    public partial class HealthAppDbContext : DbContext
    {
        public HealthAppDbContext()
            : base("name= HealthAppDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appointment> Appointments { get; set; }
        public virtual DbSet<DoctorAvailableSlot> DoctorAvailableSlots { get; set; }
        public virtual DbSet<DoctorLeaf> DoctorLeaves { get; set; }
        public virtual DbSet<Doctor> Doctors { get; set; }
        public virtual DbSet<HealthRecord> HealthRecords { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<vw_PatientHealthHistory> vw_PatientHealthHistory { get; set; }
    }
}
