//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthCareApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthRecord
    {
        public int RecordId { get; set; }
        public int AppointmentId { get; set; }
        public System.DateTime VisitDate { get; set; }
        public string Diagnosis { get; set; }
        public string Prescription { get; set; }
        public string Notes { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Appointment Appointment { get; set; }
    }
}
